spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskmanagement
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


jwt:
  secret: ay7cuTGHpdIuPVPDNV2HTT76yhgXsAl0gasOn0dar5tiV6kV6Z8V0brKlKHxwdCRSFW8X7sG2VxqTGMUwW7Gsg==
  expiration: 86400000
  refreshExpiration: 604800000 # 7 days

data:
  redis:
    host: redis
    port: 6379

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG